config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home', as: 'pages_home'
  get 'pages/posts'
  get 'pages/events'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope -> { order(date: :asc) }
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(date: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :content, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.limit(3)
    @events = Event.limit(3)
end
def posts
    @posts = Post.all
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.content %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RNMA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <br><br><br>
    <%= yield %>
  </body>
</html>

app/views/pages/events.html.erb
<section class="hero is-background-color-primary is-small">
  <div class="hero-body has-text-centered">
      <p class="title is-2 is-family-primary">
        Agenda
      </p>
  </div>
</section>

app/views/pages/home.html.erb
<%= render 'partials/banner' %>
<%= render partial: 'partials/posts', locals: { posts: @posts } %>
<%= render 'partials/agenda' %>

app/views/pages/posts.html.erb
<section class="hero is-background-color-secondary is-small">
    <div class="hero-body has-text-centered">
        <p class="title is-2 is-family-primary">
            Actualités
        </p>
    </div>
</section>

<div class="is-ancestor">
    <% @posts.each_with_index do |post,index| %>
        <% if index % 4 == 0 %>
            <div class="tile mx-5">
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
        <% elsif index % 4 == 3 %>
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
            </div>
        <% else %>
            <%= render partial: 'partials/post_tile', locals: { post: post } %>
        <% end %>
    <% end %>
</div>

<%#= render 'partials/pagination' %>

<!-- TODO
boucler for(i=0 ; i<4 ; i++){
    parcourir Post{
        créer une div "tile is-ancestor is-vertical is-gapless mx-5"
            tous les modulo 4=i{
                render partial
            }
        </div>
    }
}
-->

app/views/partials/_agenda.html.erb
<div class="columns is-mobile">
    <div class="column is-half is-offset-one-quarter">
        <p class="title is-2 has-text-centered">
            Agenda
        </p>

        <table>
            <tbody>
                <% @events.each do |event| %>
                    <tr class="box tr-border">
                        <td class="subtitle is-7 has-text-weight-normal">
                            <p>
                                <%= event.date.day %>
                            </p>
                            <p>
                                <%= l event.date, format: :month %>
                            </p>
                            <p>
                                <%= event.date.year %>
                            </p>
                        </td>
                        <td>
                            <p class="title is-4">
                                <%= event.title %>
                            </p>
                            <p class="content">
                                <%= truncate(strip_tags(event.content), length: 120) %>
                            </p>
                            <%= link_to "Lire la suite", event, class: "content has-text-danger has-text-centered" %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/partials/_banner.html.erb
<section class="hero is-fullheight">
  <div class="hero-body hero-background">
    <div class="column is-half ml-6">
      <p class="title is-1 mb-6">
        Bienvenue sur le site du Réseau National des Maisons des Associations
      </p>
      <p class="subtitle">
        Retrouver sur ce site tout ce qui est en lien avec le Réseau National des Maisons des Associations
      </p>
    </div>
    <div class="column ml-7">
      <figure>
        <%= image_tag "logo.png" %>
      </figure>
    </div>
  </div>
</section>

app/views/partials/_nav.html.erb
<nav class="navbar is-fixed-top is-transparent" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href=<%= pages_home_path %>>
      <%= image_tag('logo.png') %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href=<%= pages_home_path %>>
        Accueil
      </a>
      <a class="navbar-item" href=<%= pages_posts_path %>>
        Actualités
      </a>
      <a class="navbar-item" href=<%= pages_events_path %>>
        Agenda
      </a>

    </div>
  </div>
  </nav>

app/views/partials/_post_card.html.erb
<div class="column is-one-third">
    <div class="card">

        <div class="card-image">
            <figure class="image is-256x256">
                <%= image_tag 'placeholder_post' %>
                <div class="is-danger-image-hover">
                </div>
            </figure>
        </div>

        <div class="card-content">
            <p class="title is-5 card-footer-border-top is-danger-text-hover has-text-centered">
                <%= post.title %>
            </p>
            <p class="subtitle is-7 has-text-weight-normal has-text-centered">
                <%= l post.date %>
            </p>
            <div class="content">
                <p class="content has-text-centered">
                    <%= truncate(strip_tags(post.content), length: 120) %>
                </p>
            </div>
            
        </div>

        <footer class="card-footer">
            <%= link_to "Lire la suite", post, class: "content card-footer-item has-text-danger has-text-centered" %>
        </footer>
    </div>
</div>

app/views/partials/_post_tile.html.erb
<div class="tile is-parent is-3 p-1">
    <article class="tile is-child box p-0 has-background-white-ter">
        <figure class="image is-256x256">
            <%= image_tag 'placeholder_post' %>
        </figure>
        <div class="p-2">
            <p class="title is-4 is-danger-text-hover">
                <%= post.title %>
            </p>
            <!--<p class="subtitle is-7"><%= l post.date %></p>-->
            <div class="content">
                <p class="content">
                    <%= truncate(strip_tags(post.content), length: 300) %>
                </p>
                <%= link_to "Lire la suite", post, class: "content has-text-danger" %>
            </div>
        </div>
    </article>
</div>

app/views/partials/_posts.html.erb
<div class="post">

  <p class="title is-2 mt-3 has-text-centered">
    Actualités
  </p>

  <div class="columns mx-6 is-desktop">
        <% @posts.each do |post| %>
          <%= render partial: 'partials/post_card', locals: { post: post } %>
        <% end %>
  </div>

  <section class="hero is-link is-small">
    <div class="hero-body">
      <div class="container has-text-centered">
        <button class="button is-color-secondary is-centered">
          <%= link_to 'Toutes les actualités', pages_posts_path %>
        </button>
      </div>
    </div>
  </section>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.date %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>